origin-cert:
  data:
    "server.key": "${certificate_key}"
    "server.crt": "${certificate_cert}"

argocd-secret:
  labels:
    app.kubernetes.io/part-of: argocd

  data:
    "server.secretkey": "${argocd_server_secret}"
    "admin.password": "${argocd_admin_password}"
